// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaVjencanja.Data;

#nullable disable

namespace rezervacija_vjencanja_be.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506104933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartnerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasBooking = true,
                            Name = "BAND"
                        },
                        new
                        {
                            Id = 2,
                            HasBooking = false,
                            Name = "FLORIST"
                        },
                        new
                        {
                            Id = 3,
                            HasBooking = false,
                            Name = "PASTRY"
                        },
                        new
                        {
                            Id = 4,
                            HasBooking = true,
                            Name = "PHOTOGRAPHER"
                        },
                        new
                        {
                            Id = 5,
                            HasBooking = true,
                            Name = "VENUE"
                        },
                        new
                        {
                            Id = 6,
                            HasBooking = false,
                            Name = "CATERING"
                        },
                        new
                        {
                            Id = 7,
                            HasBooking = false,
                            Name = "GENERIC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
