// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaVjencanja.Data;

#nullable disable

namespace rezervacija_vjencanja_be.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezervacijaVjencanja.Entities.BandMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("IX_BandMembers_PartnerId");

                    b.ToTable("BandMembers", (string)null);
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeddingId")
                        .HasColumnType("int");

                    b.Property<int>("WeddingPartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("IX_Bookings_PartnerId");

                    b.HasIndex("WeddingId")
                        .HasDatabaseName("IX_Bookings_WeddingId");

                    b.HasIndex("WeddingPartnerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Bookings_WeddingPartner");

                    b.HasIndex("PartnerId", "StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_Bookings_DateRange");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Bookings_DateRange", "EndDateTime > StartDateTime");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CommissionPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExtraFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Partners_IsActive");

                    b.HasIndex("PartnerTypeId")
                        .HasDatabaseName("IX_Partners_PartnerTypeId");

                    b.ToTable("Partners", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Partners_Commission", "CommissionPercent >= 0 AND CommissionPercent <= 100");

                            t.HasCheckConstraint("CHK_Partners_ExtraFields_JSON", "ExtraFields IS NULL OR ISJSON(ExtraFields) = 1");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("SERVICE");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PartnerCatalogItems_IsActive");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("IX_PartnerCatalogItems_ItemType");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("IX_PartnerCatalogItems_PartnerId");

                    b.ToTable("PartnerCatalogItems", null, t =>
                        {
                            t.HasCheckConstraint("CHK_PartnerCatalogItems_BasePrice", "BasePrice IS NULL OR BasePrice >= 0");

                            t.HasCheckConstraint("CHK_PartnerCatalogItems_ItemType", "ItemType IN ('SERVICE', 'PRODUCT', 'SONG')");

                            t.HasCheckConstraint("CHK_PartnerCatalogItems_Metadata", "Metadata IS NULL OR ISJSON(Metadata) = 1");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FieldSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_PartnerTypes_Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartnerTypes", null, t =>
                        {
                            t.HasCheckConstraint("CHK_PartnerTypes_JSON", "FieldSchema IS NULL OR ISJSON(FieldSchema) = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BAND",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = true,
                            Name = "Bend / DJ"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FLORIST",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = false,
                            Name = "Cvjećar"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PASTRY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = false,
                            Name = "Slastičar"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PHOTOGRAPHER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = true,
                            Name = "Fotograf / Snimatelj"
                        },
                        new
                        {
                            Id = 5,
                            Code = "VENUE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = true,
                            Name = "Sala / Dvorana"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CATERING",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = false,
                            Name = "Catering"
                        },
                        new
                        {
                            Id = 7,
                            Code = "GENERIC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasBooking = false,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<byte?>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId")
                        .HasDatabaseName("IX_PricingRules_CatalogItemId");

                    b.HasIndex("RuleType")
                        .HasDatabaseName("IX_PricingRules_RuleType");

                    b.ToTable("PricingRules", null, t =>
                        {
                            t.HasCheckConstraint("CHK_PricingRules_DateRange", "ValidFrom IS NULL OR ValidTo IS NULL OR ValidFrom <= ValidTo");

                            t.HasCheckConstraint("CHK_PricingRules_DayOfWeek", "DayOfWeek IS NULL OR (DayOfWeek >= 1 AND DayOfWeek <= 7)");

                            t.HasCheckConstraint("CHK_PricingRules_Price", "Price >= 0");

                            t.HasCheckConstraint("CHK_PricingRules_RuleType", "RuleType IN ('SPECIAL_DAY', 'SPECIFIC_DATE')");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Wedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PREPARATION");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DateTime")
                        .HasDatabaseName("IX_Weddings_DateTime");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Weddings_Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("Weddings", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Weddings_Status", "Status IN ('PREPARATION', 'CONFIRMED', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.WeddingPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PlannedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PROPOSED");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("WeddingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("IX_WeddingPartners_PartnerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WeddingPartners_Status");

                    b.HasIndex("WeddingId")
                        .HasDatabaseName("IX_WeddingPartners_WeddingId");

                    b.ToTable("WeddingPartners", null, t =>
                        {
                            t.HasCheckConstraint("CHK_WeddingPartners_ActualPrice", "ActualPrice IS NULL OR ActualPrice >= 0");

                            t.HasCheckConstraint("CHK_WeddingPartners_CommissionPercent", "CommissionPercent IS NULL OR (CommissionPercent >= 0 AND CommissionPercent <= 100)");

                            t.HasCheckConstraint("CHK_WeddingPartners_Status", "Status IN ('PROPOSED', 'OFFERED', 'CONFIRMED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.WeddingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DefaultNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequiredPartnerTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeddingTemplates", null, t =>
                        {
                            t.HasCheckConstraint("CHK_WeddingTemplates_ActivityOrder_JSON", "ActivityOrder IS NULL OR ISJSON(ActivityOrder) = 1");

                            t.HasCheckConstraint("CHK_WeddingTemplates_PartnerTypes_JSON", "RequiredPartnerTypes IS NULL OR ISJSON(RequiredPartnerTypes) = 1");
                        });
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.BandMember", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.Partner", "Partner")
                        .WithMany("BandMembers")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Booking", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RezervacijaVjencanja.Entities.Wedding", "Wedding")
                        .WithMany()
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RezervacijaVjencanja.Entities.WeddingPartner", "WeddingPartner")
                        .WithOne("Booking")
                        .HasForeignKey("RezervacijaVjencanja.Entities.Booking", "WeddingPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Wedding");

                    b.Navigation("WeddingPartner");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Partner", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.PartnerType", "PartnerType")
                        .WithMany("Partners")
                        .HasForeignKey("PartnerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartnerType");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerCatalogItem", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.Partner", "Partner")
                        .WithMany("CatalogItems")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PricingRule", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.PartnerCatalogItem", "CatalogItem")
                        .WithMany("PricingRules")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Wedding", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.WeddingTemplate", "Template")
                        .WithMany("Weddings")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.WeddingPartner", b =>
                {
                    b.HasOne("RezervacijaVjencanja.Entities.PartnerCatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RezervacijaVjencanja.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RezervacijaVjencanja.Entities.Wedding", "Wedding")
                        .WithMany("WeddingPartners")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Partner");

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Partner", b =>
                {
                    b.Navigation("BandMembers");

                    b.Navigation("CatalogItems");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerCatalogItem", b =>
                {
                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.PartnerType", b =>
                {
                    b.Navigation("Partners");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.Wedding", b =>
                {
                    b.Navigation("WeddingPartners");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.WeddingPartner", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RezervacijaVjencanja.Entities.WeddingTemplate", b =>
                {
                    b.Navigation("Weddings");
                });
#pragma warning restore 612, 618
        }
    }
}
