// This file is generated by running "npm run sync-schema". Do not modify it manually.
export interface paths {
    "/api/partners/{partnerId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfBandMemberDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBandMemberRequest"];
                    "text/json": components["schemas"]["CreateBandMemberRequest"];
                    "application/*+json": components["schemas"]["CreateBandMemberRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{partnerId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                    memberId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBandMemberRequest"];
                    "text/json": components["schemas"]["UpdateBandMemberRequest"];
                    "application/*+json": components["schemas"]["UpdateBandMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "application/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                        "text/json": components["schemas"]["ApiResponseOfBandMemberDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                    memberId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{partnerId}/catalog-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfCatalogItemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCatalogItemRequest"];
                    "text/json": components["schemas"]["UpdateCatalogItemRequest"];
                    "application/*+json": components["schemas"]["UpdateCatalogItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCatalogItemRequest"];
                    "text/json": components["schemas"]["CreateCatalogItemRequest"];
                    "application/*+json": components["schemas"]["CreateCatalogItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfCatalogItemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{partnerId}/catalog/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                        "application/json": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                        "text/json": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                        "application/json": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                        "text/json": components["schemas"]["ApiResponseOfCsvPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{partnerId}/catalog/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    } & {
                        mapping?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCsvImportResponse"];
                        "application/json": components["schemas"]["ApiResponseOfCsvImportResponse"];
                        "text/json": components["schemas"]["ApiResponseOfCsvImportResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCsvImportResponse"];
                        "application/json": components["schemas"]["ApiResponseOfCsvImportResponse"];
                        "text/json": components["schemas"]["ApiResponseOfCsvImportResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{partnerId}/catalog/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    partnerTypeId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfPartnerListDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPartnerListDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfPartnerListDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartnerRequest"];
                    "text/json": components["schemas"]["CreatePartnerRequest"];
                    "application/*+json": components["schemas"]["CreatePartnerRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePartnerRequest"];
                    "text/json": components["schemas"]["UpdatePartnerRequest"];
                    "application/*+json": components["schemas"]["UpdatePartnerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfBookingDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAvailabilityDto"];
                        "application/json": components["schemas"]["ApiResponseOfAvailabilityDto"];
                        "text/json": components["schemas"]["ApiResponseOfAvailabilityDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAvailabilityDto"];
                        "application/json": components["schemas"]["ApiResponseOfAvailabilityDto"];
                        "text/json": components["schemas"]["ApiResponseOfAvailabilityDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfPartnerTypeDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartnerTypeRequest"];
                    "text/json": components["schemas"]["CreatePartnerTypeRequest"];
                    "application/*+json": components["schemas"]["CreatePartnerTypeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePartnerTypeRequest"];
                    "text/json": components["schemas"]["UpdatePartnerTypeRequest"];
                    "application/*+json": components["schemas"]["UpdatePartnerTypeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "application/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                        "text/json": components["schemas"]["ApiResponseOfPartnerTypeDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog-items/{catalogItemId}/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    catalogItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfPricingRuleDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePricingRuleRequest"];
                    "text/json": components["schemas"]["CreatePricingRuleRequest"];
                    "application/*+json": components["schemas"]["CreatePricingRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePricingRuleRequest"];
                    "text/json": components["schemas"]["UpdatePricingRuleRequest"];
                    "application/*+json": components["schemas"]["UpdatePricingRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "application/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                        "text/json": components["schemas"]["ApiResponseOfPricingRuleDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weddings/{id}/partners/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseOfAvailabilityDto: {
            data: components["schemas"]["AvailabilityDto"];
            error: string | null;
        };
        ApiResponseOfBandMemberDto: {
            data: components["schemas"]["BandMemberDto2"];
            error: string | null;
        };
        ApiResponseOfboolean: {
            data: boolean;
            error: string | null;
        };
        ApiResponseOfCatalogItemDto: {
            data: components["schemas"]["CatalogItemDto2"];
            error: string | null;
        };
        ApiResponseOfCsvImportResponse: {
            data: components["schemas"]["CsvImportResponse"];
            error: string | null;
        };
        ApiResponseOfCsvPreviewResponse: {
            data: components["schemas"]["CsvPreviewResponse"];
            error: string | null;
        };
        ApiResponseOfIEnumerableOfBandMemberDto: {
            data: components["schemas"]["BandMemberDto"][] | null;
            error: string | null;
        };
        ApiResponseOfIEnumerableOfBookingDto: {
            data: components["schemas"]["BookingDto"][] | null;
            error: string | null;
        };
        ApiResponseOfIEnumerableOfCatalogItemDto: {
            data: components["schemas"]["CatalogItemDto"][] | null;
            error: string | null;
        };
        ApiResponseOfIEnumerableOfPartnerListDto: {
            data: components["schemas"]["PartnerListDto"][] | null;
            error: string | null;
        };
        ApiResponseOfIEnumerableOfPartnerTypeDto: {
            data: components["schemas"]["PartnerTypeDto"][] | null;
            error: string | null;
        };
        ApiResponseOfIEnumerableOfPricingRuleDto: {
            data: components["schemas"]["PricingRuleDto"][] | null;
            error: string | null;
        };
        ApiResponseOfPartnerDto: {
            data: components["schemas"]["PartnerDto"];
            error: string | null;
        };
        ApiResponseOfPartnerTypeDto: {
            data: components["schemas"]["PartnerTypeDto2"];
            error: string | null;
        };
        ApiResponseOfPricingRuleDto: {
            data: components["schemas"]["PricingRuleDto2"];
            error: string | null;
        };
        AvailabilityDto: {
            available: boolean;
            conflicts: components["schemas"]["BookingDto"][];
        } | null;
        BandMemberDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            partnerId: number;
            name: string;
            role: string | null;
            phone: string | null;
            email: string | null;
        };
        BandMemberDto2: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            partnerId: number;
            name: string;
            role: string | null;
            phone: string | null;
            email: string | null;
        } | null;
        BookingDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            partnerId: number;
            /** Format: int32 */
            weddingId: number;
            weddingName: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
            weddingPartnerStatus: string;
            notes: string | null;
        };
        CatalogItemDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            partnerId: number;
            name: string;
            category: string | null;
            description: string | null;
            itemType: string;
            /** Format: double */
            basePrice: number | null;
            metadata: string | null;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        CatalogItemDto2: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            partnerId: number;
            name: string;
            category: string | null;
            description: string | null;
            itemType: string;
            /** Format: double */
            basePrice: number | null;
            metadata: string | null;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
        } | null;
        CreateBandMemberRequest: {
            name: string;
            role: string | null;
            phone: string | null;
            email: string | null;
        };
        CreateCatalogItemRequest: {
            /** Format: int32 */
            partnerId: number;
            name: string;
            category: string | null;
            description: string | null;
            itemType: string;
            /** Format: double */
            basePrice: number | null;
            metadata: string | null;
        };
        CreatePartnerRequest: {
            name: string;
            /** Format: int32 */
            partnerTypeId: number;
            address: string | null;
            phone: string | null;
            email: string | null;
            website: string | null;
            /** Format: double */
            commissionPercent: number;
            notes: string | null;
            extraFields: string | null;
        };
        CreatePartnerTypeRequest: {
            name: string;
            code: string;
            hasBooking: boolean;
            fieldSchema: string | null;
        };
        CreatePricingRuleRequest: {
            /** Format: int32 */
            catalogItemId: number;
            ruleType: string;
            /** Format: uint8 */
            dayOfWeek: number | null;
            /** Format: date */
            specificDate: string | null;
            /** Format: double */
            price: number;
            /** Format: date */
            validFrom: string | null;
            /** Format: date */
            validTo: string | null;
        };
        CsvImportResponse: {
            /** Format: int32 */
            imported: number;
            /** Format: int32 */
            skipped: number;
            skippedRows: components["schemas"]["CsvImportSkippedRow"][];
        } | null;
        CsvImportSkippedRow: {
            /** Format: int32 */
            rowNumber: number;
            reason: string;
        };
        CsvPreviewResponse: {
            headers: string[];
            preview: string[][];
        } | null;
        /** Format: binary */
        IFormFile: string;
        PartnerDto: {
            /** Format: int32 */
            id: number;
            name: string;
            address: string | null;
            phone: string | null;
            email: string | null;
            website: string | null;
            /** Format: int32 */
            partnerTypeId: number;
            partnerTypeCode: string;
            partnerTypeName: string;
            /** Format: double */
            commissionPercent: number;
            notes: string | null;
            extraFields: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        } | null;
        PartnerListDto: {
            /** Format: int32 */
            id: number;
            name: string;
            partnerTypeCode: string;
            partnerTypeName: string;
            /** Format: double */
            commissionPercent: number;
            isActive: boolean;
        };
        PartnerTypeDto: {
            /** Format: int32 */
            id: number;
            name: string;
            code: string;
            hasBooking: boolean;
            fieldSchema: string | null;
        };
        PartnerTypeDto2: {
            /** Format: int32 */
            id: number;
            name: string;
            code: string;
            hasBooking: boolean;
            fieldSchema: string | null;
        } | null;
        PricingRuleDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            catalogItemId: number;
            ruleType: string;
            /** Format: uint8 */
            dayOfWeek: number | null;
            /** Format: date */
            specificDate: string | null;
            /** Format: double */
            price: number;
            /** Format: date */
            validFrom: string | null;
            /** Format: date */
            validTo: string | null;
        };
        PricingRuleDto2: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            catalogItemId: number;
            ruleType: string;
            /** Format: uint8 */
            dayOfWeek: number | null;
            /** Format: date */
            specificDate: string | null;
            /** Format: double */
            price: number;
            /** Format: date */
            validFrom: string | null;
            /** Format: date */
            validTo: string | null;
        } | null;
        UpdateBandMemberRequest: {
            name: string;
            role: string | null;
            phone: string | null;
            email: string | null;
        };
        UpdateCatalogItemRequest: {
            name: string;
            category: string | null;
            description: string | null;
            itemType: string;
            /** Format: double */
            basePrice: number | null;
            metadata: string | null;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        UpdatePartnerRequest: {
            name: string;
            /** Format: int32 */
            partnerTypeId: number;
            address: string | null;
            phone: string | null;
            email: string | null;
            website: string | null;
            /** Format: double */
            commissionPercent: number;
            notes: string | null;
            extraFields: string | null;
            isActive: boolean;
        };
        UpdatePartnerTypeRequest: {
            name: string;
            code: string;
            hasBooking: boolean;
            fieldSchema: string | null;
        };
        UpdatePricingRuleRequest: {
            ruleType: string;
            /** Format: uint8 */
            dayOfWeek: number | null;
            /** Format: date */
            specificDate: string | null;
            /** Format: double */
            price: number;
            /** Format: date */
            validFrom: string | null;
            /** Format: date */
            validTo: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

