import * as fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";
import * as dotenv from "dotenv";

dotenv.config();

const BACKEND_URL = process.env.VITE_BACKEND_URL || "http://localhost:8080";
const OPENAPI_URL = `${BACKEND_URL}/openapi/v1.json`;

console.log(`Fetching OpenAPI spec from: ${OPENAPI_URL}`);

try {
  const ast = await openapiTS(OPENAPI_URL);

  const contents = astToString(ast);

  const outputPath = new URL("../src/types/api.d.ts", import.meta.url);
  fs.mkdirSync(new URL("../src/types/", import.meta.url), { recursive: true });

  fs.writeFileSync(
    outputPath,
    [
      '// This file is generated by running "npm run sync-schema". Do not modify it manually.',
      contents,
      "",
    ].join("\n"),
  );

  console.log("✓ API types generated successfully at src/types/api.d.ts");
} catch (error) {
  console.error("✗ Failed to generate API types:", error instanceof Error ? error.message : error);
  process.exit(1);
}
